// Complete Quran surah metadata (1-114)

export interface SurahInfo {
  id: number;
  nameArabic: string;
  nameEnglish: string;
  nameTransliteration: string;
  ayahCount: number;
  revelationType: "meccan" | "medinan";
}

export const allSurahs: SurahInfo[] = [
  { id: 1, nameArabic: "الفاتحة", nameEnglish: "The Opening", nameTransliteration: "Al-Fatihah", ayahCount: 7, revelationType: "meccan" },
  { id: 2, nameArabic: "البقرة", nameEnglish: "The Cow", nameTransliteration: "Al-Baqarah", ayahCount: 286, revelationType: "medinan" },
  { id: 3, nameArabic: "آل عمران", nameEnglish: "The Family of Imran", nameTransliteration: "Aal-Imran", ayahCount: 200, revelationType: "medinan" },
  { id: 4, nameArabic: "النساء", nameEnglish: "The Women", nameTransliteration: "An-Nisa", ayahCount: 176, revelationType: "medinan" },
  { id: 5, nameArabic: "المائدة", nameEnglish: "The Table Spread", nameTransliteration: "Al-Ma'idah", ayahCount: 120, revelationType: "medinan" },
  { id: 6, nameArabic: "الأنعام", nameEnglish: "The Cattle", nameTransliteration: "Al-An'am", ayahCount: 165, revelationType: "meccan" },
  { id: 7, nameArabic: "الأعراف", nameEnglish: "The Heights", nameTransliteration: "Al-A'raf", ayahCount: 206, revelationType: "meccan" },
  { id: 8, nameArabic: "الأنفال", nameEnglish: "The Spoils of War", nameTransliteration: "Al-Anfal", ayahCount: 75, revelationType: "medinan" },
  { id: 9, nameArabic: "التوبة", nameEnglish: "The Repentance", nameTransliteration: "At-Tawbah", ayahCount: 129, revelationType: "medinan" },
  { id: 10, nameArabic: "يونس", nameEnglish: "Jonah", nameTransliteration: "Yunus", ayahCount: 109, revelationType: "meccan" },
  { id: 11, nameArabic: "هود", nameEnglish: "Hud", nameTransliteration: "Hud", ayahCount: 123, revelationType: "meccan" },
  { id: 12, nameArabic: "يوسف", nameEnglish: "Joseph", nameTransliteration: "Yusuf", ayahCount: 111, revelationType: "meccan" },
  { id: 13, nameArabic: "الرعد", nameEnglish: "The Thunder", nameTransliteration: "Ar-Ra'd", ayahCount: 43, revelationType: "medinan" },
  { id: 14, nameArabic: "إبراهيم", nameEnglish: "Abraham", nameTransliteration: "Ibrahim", ayahCount: 52, revelationType: "meccan" },
  { id: 15, nameArabic: "الحجر", nameEnglish: "The Rocky Tract", nameTransliteration: "Al-Hijr", ayahCount: 99, revelationType: "meccan" },
  { id: 16, nameArabic: "النحل", nameEnglish: "The Bee", nameTransliteration: "An-Nahl", ayahCount: 128, revelationType: "meccan" },
  { id: 17, nameArabic: "الإسراء", nameEnglish: "The Night Journey", nameTransliteration: "Al-Isra", ayahCount: 111, revelationType: "meccan" },
  { id: 18, nameArabic: "الكهف", nameEnglish: "The Cave", nameTransliteration: "Al-Kahf", ayahCount: 110, revelationType: "meccan" },
  { id: 19, nameArabic: "مريم", nameEnglish: "Mary", nameTransliteration: "Maryam", ayahCount: 98, revelationType: "meccan" },
  { id: 20, nameArabic: "طه", nameEnglish: "Ta-Ha", nameTransliteration: "Ta-Ha", ayahCount: 135, revelationType: "meccan" },
  { id: 21, nameArabic: "الأنبياء", nameEnglish: "The Prophets", nameTransliteration: "Al-Anbiya", ayahCount: 112, revelationType: "meccan" },
  { id: 22, nameArabic: "الحج", nameEnglish: "The Pilgrimage", nameTransliteration: "Al-Hajj", ayahCount: 78, revelationType: "medinan" },
  { id: 23, nameArabic: "المؤمنون", nameEnglish: "The Believers", nameTransliteration: "Al-Mu'minun", ayahCount: 118, revelationType: "meccan" },
  { id: 24, nameArabic: "النور", nameEnglish: "The Light", nameTransliteration: "An-Nur", ayahCount: 64, revelationType: "medinan" },
  { id: 25, nameArabic: "الفرقان", nameEnglish: "The Criterion", nameTransliteration: "Al-Furqan", ayahCount: 77, revelationType: "meccan" },
  { id: 26, nameArabic: "الشعراء", nameEnglish: "The Poets", nameTransliteration: "Ash-Shu'ara", ayahCount: 227, revelationType: "meccan" },
  { id: 27, nameArabic: "النمل", nameEnglish: "The Ant", nameTransliteration: "An-Naml", ayahCount: 93, revelationType: "meccan" },
  { id: 28, nameArabic: "القصص", nameEnglish: "The Stories", nameTransliteration: "Al-Qasas", ayahCount: 88, revelationType: "meccan" },
  { id: 29, nameArabic: "العنكبوت", nameEnglish: "The Spider", nameTransliteration: "Al-Ankabut", ayahCount: 69, revelationType: "meccan" },
  { id: 30, nameArabic: "الروم", nameEnglish: "The Romans", nameTransliteration: "Ar-Rum", ayahCount: 60, revelationType: "meccan" },
  { id: 31, nameArabic: "لقمان", nameEnglish: "Luqman", nameTransliteration: "Luqman", ayahCount: 34, revelationType: "meccan" },
  { id: 32, nameArabic: "السجدة", nameEnglish: "The Prostration", nameTransliteration: "As-Sajdah", ayahCount: 30, revelationType: "meccan" },
  { id: 33, nameArabic: "الأحزاب", nameEnglish: "The Combined Forces", nameTransliteration: "Al-Ahzab", ayahCount: 73, revelationType: "medinan" },
  { id: 34, nameArabic: "سبأ", nameEnglish: "Sheba", nameTransliteration: "Saba", ayahCount: 54, revelationType: "meccan" },
  { id: 35, nameArabic: "فاطر", nameEnglish: "The Originator", nameTransliteration: "Fatir", ayahCount: 45, revelationType: "meccan" },
  { id: 36, nameArabic: "يس", nameEnglish: "Ya-Sin", nameTransliteration: "Ya-Sin", ayahCount: 83, revelationType: "meccan" },
  { id: 37, nameArabic: "الصافات", nameEnglish: "Those Who Set The Ranks", nameTransliteration: "As-Saffat", ayahCount: 182, revelationType: "meccan" },
  { id: 38, nameArabic: "ص", nameEnglish: "Sad", nameTransliteration: "Sad", ayahCount: 88, revelationType: "meccan" },
  { id: 39, nameArabic: "الزمر", nameEnglish: "The Troops", nameTransliteration: "Az-Zumar", ayahCount: 75, revelationType: "meccan" },
  { id: 40, nameArabic: "غافر", nameEnglish: "The Forgiver", nameTransliteration: "Ghafir", ayahCount: 85, revelationType: "meccan" },
  { id: 41, nameArabic: "فصلت", nameEnglish: "Explained in Detail", nameTransliteration: "Fussilat", ayahCount: 54, revelationType: "meccan" },
  { id: 42, nameArabic: "الشورى", nameEnglish: "The Consultation", nameTransliteration: "Ash-Shura", ayahCount: 53, revelationType: "meccan" },
  { id: 43, nameArabic: "الزخرف", nameEnglish: "The Ornaments of Gold", nameTransliteration: "Az-Zukhruf", ayahCount: 89, revelationType: "meccan" },
  { id: 44, nameArabic: "الدخان", nameEnglish: "The Smoke", nameTransliteration: "Ad-Dukhan", ayahCount: 59, revelationType: "meccan" },
  { id: 45, nameArabic: "الجاثية", nameEnglish: "The Crouching", nameTransliteration: "Al-Jathiyah", ayahCount: 37, revelationType: "meccan" },
  { id: 46, nameArabic: "الأحقاف", nameEnglish: "The Wind-Curved Sandhills", nameTransliteration: "Al-Ahqaf", ayahCount: 35, revelationType: "meccan" },
  { id: 47, nameArabic: "محمد", nameEnglish: "Muhammad", nameTransliteration: "Muhammad", ayahCount: 38, revelationType: "medinan" },
  { id: 48, nameArabic: "الفتح", nameEnglish: "The Victory", nameTransliteration: "Al-Fath", ayahCount: 29, revelationType: "medinan" },
  { id: 49, nameArabic: "الحجرات", nameEnglish: "The Rooms", nameTransliteration: "Al-Hujurat", ayahCount: 18, revelationType: "medinan" },
  { id: 50, nameArabic: "ق", nameEnglish: "Qaf", nameTransliteration: "Qaf", ayahCount: 45, revelationType: "meccan" },
  { id: 51, nameArabic: "الذاريات", nameEnglish: "The Winnowing Winds", nameTransliteration: "Adh-Dhariyat", ayahCount: 60, revelationType: "meccan" },
  { id: 52, nameArabic: "الطور", nameEnglish: "The Mount", nameTransliteration: "At-Tur", ayahCount: 49, revelationType: "meccan" },
  { id: 53, nameArabic: "النجم", nameEnglish: "The Star", nameTransliteration: "An-Najm", ayahCount: 62, revelationType: "meccan" },
  { id: 54, nameArabic: "القمر", nameEnglish: "The Moon", nameTransliteration: "Al-Qamar", ayahCount: 55, revelationType: "meccan" },
  { id: 55, nameArabic: "الرحمن", nameEnglish: "The Beneficent", nameTransliteration: "Ar-Rahman", ayahCount: 78, revelationType: "medinan" },
  { id: 56, nameArabic: "الواقعة", nameEnglish: "The Inevitable", nameTransliteration: "Al-Waqi'ah", ayahCount: 96, revelationType: "meccan" },
  { id: 57, nameArabic: "الحديد", nameEnglish: "The Iron", nameTransliteration: "Al-Hadid", ayahCount: 29, revelationType: "medinan" },
  { id: 58, nameArabic: "المجادلة", nameEnglish: "The Pleading Woman", nameTransliteration: "Al-Mujadila", ayahCount: 22, revelationType: "medinan" },
  { id: 59, nameArabic: "الحشر", nameEnglish: "The Exile", nameTransliteration: "Al-Hashr", ayahCount: 24, revelationType: "medinan" },
  { id: 60, nameArabic: "الممتحنة", nameEnglish: "She That Is To Be Examined", nameTransliteration: "Al-Mumtahanah", ayahCount: 13, revelationType: "medinan" },
  { id: 61, nameArabic: "الصف", nameEnglish: "The Ranks", nameTransliteration: "As-Saff", ayahCount: 14, revelationType: "medinan" },
  { id: 62, nameArabic: "الجمعة", nameEnglish: "The Congregation", nameTransliteration: "Al-Jumu'ah", ayahCount: 11, revelationType: "medinan" },
  { id: 63, nameArabic: "المنافقون", nameEnglish: "The Hypocrites", nameTransliteration: "Al-Munafiqun", ayahCount: 11, revelationType: "medinan" },
  { id: 64, nameArabic: "التغابن", nameEnglish: "The Mutual Disillusion", nameTransliteration: "At-Taghabun", ayahCount: 18, revelationType: "medinan" },
  { id: 65, nameArabic: "الطلاق", nameEnglish: "The Divorce", nameTransliteration: "At-Talaq", ayahCount: 12, revelationType: "medinan" },
  { id: 66, nameArabic: "التحريم", nameEnglish: "The Prohibition", nameTransliteration: "At-Tahrim", ayahCount: 12, revelationType: "medinan" },
  { id: 67, nameArabic: "الملك", nameEnglish: "The Sovereignty", nameTransliteration: "Al-Mulk", ayahCount: 30, revelationType: "meccan" },
  { id: 68, nameArabic: "القلم", nameEnglish: "The Pen", nameTransliteration: "Al-Qalam", ayahCount: 52, revelationType: "meccan" },
  { id: 69, nameArabic: "الحاقة", nameEnglish: "The Reality", nameTransliteration: "Al-Haqqah", ayahCount: 52, revelationType: "meccan" },
  { id: 70, nameArabic: "المعارج", nameEnglish: "The Ascending Stairways", nameTransliteration: "Al-Ma'arij", ayahCount: 44, revelationType: "meccan" },
  { id: 71, nameArabic: "نوح", nameEnglish: "Noah", nameTransliteration: "Nuh", ayahCount: 28, revelationType: "meccan" },
  { id: 72, nameArabic: "الجن", nameEnglish: "The Jinn", nameTransliteration: "Al-Jinn", ayahCount: 28, revelationType: "meccan" },
  { id: 73, nameArabic: "المزمل", nameEnglish: "The Enshrouded One", nameTransliteration: "Al-Muzzammil", ayahCount: 20, revelationType: "meccan" },
  { id: 74, nameArabic: "المدثر", nameEnglish: "The Cloaked One", nameTransliteration: "Al-Muddaththir", ayahCount: 56, revelationType: "meccan" },
  { id: 75, nameArabic: "القيامة", nameEnglish: "The Resurrection", nameTransliteration: "Al-Qiyamah", ayahCount: 40, revelationType: "meccan" },
  { id: 76, nameArabic: "الإنسان", nameEnglish: "The Man", nameTransliteration: "Al-Insan", ayahCount: 31, revelationType: "medinan" },
  { id: 77, nameArabic: "المرسلات", nameEnglish: "The Emissaries", nameTransliteration: "Al-Mursalat", ayahCount: 50, revelationType: "meccan" },
  { id: 78, nameArabic: "النبأ", nameEnglish: "The Tidings", nameTransliteration: "An-Naba", ayahCount: 40, revelationType: "meccan" },
  { id: 79, nameArabic: "النازعات", nameEnglish: "Those Who Pull Out", nameTransliteration: "An-Nazi'at", ayahCount: 46, revelationType: "meccan" },
  { id: 80, nameArabic: "عبس", nameEnglish: "He Frowned", nameTransliteration: "'Abasa", ayahCount: 42, revelationType: "meccan" },
  { id: 81, nameArabic: "التكوير", nameEnglish: "The Overthrowing", nameTransliteration: "At-Takwir", ayahCount: 29, revelationType: "meccan" },
  { id: 82, nameArabic: "الانفطار", nameEnglish: "The Cleaving", nameTransliteration: "Al-Infitar", ayahCount: 19, revelationType: "meccan" },
  { id: 83, nameArabic: "المطففين", nameEnglish: "The Defrauders", nameTransliteration: "Al-Mutaffifin", ayahCount: 36, revelationType: "meccan" },
  { id: 84, nameArabic: "الانشقاق", nameEnglish: "The Splitting Asunder", nameTransliteration: "Al-Inshiqaq", ayahCount: 25, revelationType: "meccan" },
  { id: 85, nameArabic: "البروج", nameEnglish: "The Mansions of the Stars", nameTransliteration: "Al-Buruj", ayahCount: 22, revelationType: "meccan" },
  { id: 86, nameArabic: "الطارق", nameEnglish: "The Morning Star", nameTransliteration: "At-Tariq", ayahCount: 17, revelationType: "meccan" },
  { id: 87, nameArabic: "الأعلى", nameEnglish: "The Most High", nameTransliteration: "Al-A'la", ayahCount: 19, revelationType: "meccan" },
  { id: 88, nameArabic: "الغاشية", nameEnglish: "The Overwhelming", nameTransliteration: "Al-Ghashiyah", ayahCount: 26, revelationType: "meccan" },
  { id: 89, nameArabic: "الفجر", nameEnglish: "The Dawn", nameTransliteration: "Al-Fajr", ayahCount: 30, revelationType: "meccan" },
  { id: 90, nameArabic: "البلد", nameEnglish: "The City", nameTransliteration: "Al-Balad", ayahCount: 20, revelationType: "meccan" },
  { id: 91, nameArabic: "الشمس", nameEnglish: "The Sun", nameTransliteration: "Ash-Shams", ayahCount: 15, revelationType: "meccan" },
  { id: 92, nameArabic: "الليل", nameEnglish: "The Night", nameTransliteration: "Al-Layl", ayahCount: 21, revelationType: "meccan" },
  { id: 93, nameArabic: "الضحى", nameEnglish: "The Morning Hours", nameTransliteration: "Ad-Duha", ayahCount: 11, revelationType: "meccan" },
  { id: 94, nameArabic: "الشرح", nameEnglish: "The Relief", nameTransliteration: "Ash-Sharh", ayahCount: 8, revelationType: "meccan" },
  { id: 95, nameArabic: "التين", nameEnglish: "The Fig", nameTransliteration: "At-Tin", ayahCount: 8, revelationType: "meccan" },
  { id: 96, nameArabic: "العلق", nameEnglish: "The Clot", nameTransliteration: "Al-'Alaq", ayahCount: 19, revelationType: "meccan" },
  { id: 97, nameArabic: "القدر", nameEnglish: "The Power", nameTransliteration: "Al-Qadr", ayahCount: 5, revelationType: "meccan" },
  { id: 98, nameArabic: "البينة", nameEnglish: "The Clear Proof", nameTransliteration: "Al-Bayyinah", ayahCount: 8, revelationType: "medinan" },
  { id: 99, nameArabic: "الزلزلة", nameEnglish: "The Earthquake", nameTransliteration: "Az-Zalzalah", ayahCount: 8, revelationType: "medinan" },
  { id: 100, nameArabic: "العاديات", nameEnglish: "The Courser", nameTransliteration: "Al-'Adiyat", ayahCount: 11, revelationType: "meccan" },
  { id: 101, nameArabic: "القارعة", nameEnglish: "The Calamity", nameTransliteration: "Al-Qari'ah", ayahCount: 11, revelationType: "meccan" },
  { id: 102, nameArabic: "التكاثر", nameEnglish: "The Rivalry in World Increase", nameTransliteration: "At-Takathur", ayahCount: 8, revelationType: "meccan" },
  { id: 103, nameArabic: "العصر", nameEnglish: "The Declining Day", nameTransliteration: "Al-'Asr", ayahCount: 3, revelationType: "meccan" },
  { id: 104, nameArabic: "الهمزة", nameEnglish: "The Traducer", nameTransliteration: "Al-Humazah", ayahCount: 9, revelationType: "meccan" },
  { id: 105, nameArabic: "الفيل", nameEnglish: "The Elephant", nameTransliteration: "Al-Fil", ayahCount: 5, revelationType: "meccan" },
  { id: 106, nameArabic: "قريش", nameEnglish: "Quraysh", nameTransliteration: "Quraysh", ayahCount: 4, revelationType: "meccan" },
  { id: 107, nameArabic: "الماعون", nameEnglish: "The Small Kindnesses", nameTransliteration: "Al-Ma'un", ayahCount: 7, revelationType: "meccan" },
  { id: 108, nameArabic: "الكوثر", nameEnglish: "The Abundance", nameTransliteration: "Al-Kawthar", ayahCount: 3, revelationType: "meccan" },
  { id: 109, nameArabic: "الكافرون", nameEnglish: "The Disbelievers", nameTransliteration: "Al-Kafirun", ayahCount: 6, revelationType: "meccan" },
  { id: 110, nameArabic: "النصر", nameEnglish: "The Divine Support", nameTransliteration: "An-Nasr", ayahCount: 3, revelationType: "medinan" },
  { id: 111, nameArabic: "المسد", nameEnglish: "The Palm Fiber", nameTransliteration: "Al-Masad", ayahCount: 5, revelationType: "meccan" },
  { id: 112, nameArabic: "الإخلاص", nameEnglish: "The Sincerity", nameTransliteration: "Al-Ikhlas", ayahCount: 4, revelationType: "meccan" },
  { id: 113, nameArabic: "الفلق", nameEnglish: "The Daybreak", nameTransliteration: "Al-Falaq", ayahCount: 5, revelationType: "meccan" },
  { id: 114, nameArabic: "الناس", nameEnglish: "Mankind", nameTransliteration: "An-Nas", ayahCount: 6, revelationType: "medinan" },
];

function getSurahById(id: number): SurahInfo | undefined {
  return allSurahs.find((surah) => surah.id === id);
}

export function getSurahName(id: number, locale: "en" | "ar"): string {
  const surah = getSurahById(id);
  if (!surah) return `Surah ${id}`;
  return locale === "ar" ? surah.nameArabic : surah.nameTransliteration;
}
